<?php
// $Id$

/**
 * @file
 * Provided administration interface for Simple Geo Tiles Service.
 */

/**
 * Implementation of hook_menu().
 */
function simplegeo_tileservice_menu() {
  $items = array();

  $base = array(
    'access arguments' => array('administer SimpleGeo tileservice layers'),
    'file'             => 'simplegeo_tileservice_ui.admin.inc',
  );

  $items['admin/build/simplegeo-tileservice'] = array(
    'title'          => 'SimpleGeo tileservice',
    'description'    => 'Add, edit and remove layers from the system.',
    'page callback'  => 'simplegeo_tileservice_list_layer',
  ) + $base;
  $items['admin/build/simplegeo-tileservice/list'] = array(
    'title'          => 'List',
    'page callback'  => 'simplegeo_tileservice_list_layer',
    'type'           => MENU_DEFAULT_LOCAL_TASK,
    'weight'         => -10,
  ) + $base;
  $items['admin/build/simplegeo-tileservice/add'] = array(
    'title'          => 'Add layer',
    'page callback'  => 'simplegeo_tileservice_add_layer_page',
    'type'           => MENU_LOCAL_TASK,
  ) + $base;
  foreach (simplegeo_tileservice_get_layer_types() as $layer_type_name => $v) {
    $type_url_str = str_replace('_', '-', $layer_type_name);
    $items['admin/build/simplegeo-tileservice/add/'. $type_url_str] = array(
      'title' => 'Add layer',
      'page callback' => 'simplegeo_tileservice_add_layer',
      'page arguments' => array(4),
    ) + $base;
  }
  $items['admin/build/simplegeo-tileservice/%simplegeo_tileservice_layer/edit'] = array(
    'title'          => 'Edit layer',
    'page callback'  => 'simplegeo_tileservice_edit_layer',
    'page arguments' => array(3),
    'type'           => MENU_LOCAL_TASK,
  ) + $base;
  $items['admin/build/simplegeo-tileservice/%simplegeo_tileservice_layer/export'] = array(
    'title'          => 'Export layer',
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('simplegeo_tileservice_export_layer', 3),
    'type'           => MENU_LOCAL_TASK,
  ) + $base;
  $items['admin/build/simplegeo-tileservice/%simplegeo_tileservice_layer/delete'] = array(
    'title'          => 'Delete layer',
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('simplegeo_tileservice_delete_confirm_layer', 3),
    'type'           => MENU_CALLBACK,
  ) + $base;
  $items['admin/build/simplegeo-tileservice/%simplegeo_tileservice_layer/disable'] = array(
    'page callback'  => 'simplegeo_tileservice_disable_layer',
    'page arguments' => array(3),
    'type'           => MENU_CALLBACK,
  ) + $base;
  $items['admin/build/simplegeo-tileservice/%simplegeo_tileservice_layer/enable'] = array(
    'page callback'  => 'simplegeo_tileservice_enable_layer',
    'page arguments' => array(3),
    'type'           => MENU_CALLBACK,
  ) + $base;

  return $items;
}
